/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pendataan;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;

/**
 *
 * @author Gusti
 */
public class Datawarga extends javax.swing.JFrame {
    private Connection conn = new koneksi () .connect();
    private DefaultTableModel tabmode;

    /**
     * Creates new form Datawarga
     */
    public Datawarga() {
        initComponents();
        aktif();
        kosong();
        datatable();
    }
    
    protected void aktif() {
    txtKK.requestFocus();
    }
    
    protected void kosong(){
    txtKK.setText("");
    txtNama.setText("");
    txtAlamat.setText("");
    buttonGroup1.clearSelection();
    buttonGroup2.clearSelection();
    buttonGroup3.clearSelection();
    buttonGroup4.clearSelection();
    buttonGroup5.clearSelection();
    buttonGroup6.clearSelection();
    }
    
    protected void datatable(){
    Object[] Baris ={"No. KK","Nama","Alamat","Jenis Kelamin","Status Pernikahan","Jumlah Tanggungan","Usia","Jenis Pekerjaan","Pendapatan"};
    tabmode = new DefaultTableModel(null, Baris);
    String cariitem=txtCari.getText();
    
    try {
        String sql ="SELECT * FROM datawarga where nokk like '%"+cariitem+"%' or nama like '%"+cariitem+"%' order by alamat asc";
        Statement stat = conn.createStatement();
        ResultSet hasil = stat.executeQuery(sql);
        while (hasil.next()){
            tabmode.addRow(new Object[]{
                hasil.getString(1),
                hasil.getString(2),
                hasil.getString(3),
                hasil.getString(4),
                hasil.getString(5),
                hasil.getString(6),
                hasil.getString(7),
                hasil.getString(8),
                hasil.getString(9),
            });
        }
        tblDataWarga.setModel (tabmode);
      } catch (Exception e){
          JOptionPane.showMessageDialog(null, "data gagal dipanggil"+e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtKK = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        txtAlamat = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jkl = new javax.swing.JRadioButton();
        jkp = new javax.swing.JRadioButton();
        sp1 = new javax.swing.JRadioButton();
        sp2 = new javax.swing.JRadioButton();
        sp3 = new javax.swing.JRadioButton();
        sp4 = new javax.swing.JRadioButton();
        jt1 = new javax.swing.JRadioButton();
        jt2 = new javax.swing.JRadioButton();
        jt3 = new javax.swing.JRadioButton();
        jt4 = new javax.swing.JRadioButton();
        us1 = new javax.swing.JRadioButton();
        us2 = new javax.swing.JRadioButton();
        us3 = new javax.swing.JRadioButton();
        us4 = new javax.swing.JRadioButton();
        jp1a = new javax.swing.JRadioButton();
        jp2a = new javax.swing.JRadioButton();
        jp3a = new javax.swing.JRadioButton();
        jp4a = new javax.swing.JRadioButton();
        jp1b = new javax.swing.JRadioButton();
        jp2b = new javax.swing.JRadioButton();
        jp3b = new javax.swing.JRadioButton();
        jp4b = new javax.swing.JRadioButton();
        pd1 = new javax.swing.JRadioButton();
        pd2 = new javax.swing.JRadioButton();
        pd3 = new javax.swing.JRadioButton();
        pd4 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtCari = new javax.swing.JTextField();
        jToggleButton1 = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDataWarga = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 200, 126));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton4.setText("Kembali");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 28, 77, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Data Warga");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 40, -1, -1));
        jPanel1.add(txtKK, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, 146, -1));
        jPanel1.add(txtNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 146, -1));
        jPanel1.add(txtAlamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 146, -1));

        jButton1.setText("Simpan");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 110, 77, -1));

        jButton3.setText("Hapus");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 140, 77, -1));

        jkl.setBackground(new java.awt.Color(255, 200, 126));
        buttonGroup1.add(jkl);
        jkl.setText("Laki-laki");
        jPanel1.add(jkl, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, -1, -1));

        jkp.setBackground(new java.awt.Color(255, 200, 126));
        buttonGroup1.add(jkp);
        jkp.setText("Perempuan");
        jPanel1.add(jkp, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, -1, -1));

        sp1.setBackground(new java.awt.Color(255, 200, 126));
        buttonGroup2.add(sp1);
        sp1.setText("Belum Menikah");
        jPanel1.add(sp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, -1, -1));

        sp2.setBackground(new java.awt.Color(255, 200, 126));
        buttonGroup2.add(sp2);
        sp2.setText("Sudah Menikah");
        jPanel1.add(sp2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 240, -1, -1));

        sp3.setBackground(new java.awt.Color(255, 200, 126));
        buttonGroup2.add(sp3);
        sp3.setText("Cerai Hidup");
        jPanel1.add(sp3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 240, -1, -1));

        sp4.setBackground(new java.awt.Color(255, 200, 126));
        buttonGroup2.add(sp4);
        sp4.setText("Cerai Mati");
        jPanel1.add(sp4, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 240, -1, -1));

        jt1.setBackground(new java.awt.Color(255, 200, 126));
        buttonGroup3.add(jt1);
        jt1.setText("0-1");
        jPanel1.add(jt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, -1, -1));

        jt2.setBackground(new java.awt.Color(255, 200, 126));
        buttonGroup3.add(jt2);
        jt2.setText("2-3");
        jPanel1.add(jt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 270, -1, -1));

        jt3.setBackground(new java.awt.Color(255, 200, 126));
        buttonGroup3.add(jt3);
        jt3.setText("4-5");
        jPanel1.add(jt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 270, -1, -1));

        jt4.setBackground(new java.awt.Color(255, 200, 126));
        buttonGroup3.add(jt4);
        jt4.setText("Lebih dari 5");
        jPanel1.add(jt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 270, -1, -1));

        us1.setBackground(new java.awt.Color(255, 200, 126));
        buttonGroup4.add(us1);
        us1.setText("Dibawah 31");
        jPanel1.add(us1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, -1, -1));

        us2.setBackground(new java.awt.Color(255, 200, 126));
        buttonGroup4.add(us2);
        us2.setText("31-45");
        jPanel1.add(us2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 300, -1, -1));

        us3.setBackground(new java.awt.Color(255, 200, 126));
        buttonGroup4.add(us3);
        us3.setText("46-60");
        jPanel1.add(us3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 300, -1, -1));

        us4.setBackground(new java.awt.Color(255, 200, 126));
        buttonGroup4.add(us4);
        us4.setText("Diatas 60");
        jPanel1.add(us4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 300, -1, -1));

        jp1a.setBackground(new java.awt.Color(255, 200, 126));
        buttonGroup5.add(jp1a);
        jp1a.setText("Aparatur/Pejabat Negara");
        jPanel1.add(jp1a, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 330, -1, -1));

        jp2a.setBackground(new java.awt.Color(255, 200, 126));
        buttonGroup5.add(jp2a);
        jp2a.setText("Tenaga Pengajar");
        jPanel1.add(jp2a, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 330, -1, -1));

        jp3a.setBackground(new java.awt.Color(255, 200, 126));
        buttonGroup5.add(jp3a);
        jp3a.setText("Pertanian/Peternakan");
        jPanel1.add(jp3a, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 330, -1, -1));

        jp4a.setBackground(new java.awt.Color(255, 200, 126));
        buttonGroup5.add(jp4a);
        jp4a.setText("Tidak/Belum Bekerja");
        jPanel1.add(jp4a, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 330, -1, -1));

        jp1b.setBackground(new java.awt.Color(255, 200, 126));
        buttonGroup5.add(jp1b);
        jp1b.setText("Wiraswasta");
        jPanel1.add(jp1b, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 350, -1, -1));

        jp2b.setBackground(new java.awt.Color(255, 200, 126));
        buttonGroup5.add(jp2b);
        jp2b.setText("Tenaga Kesehatan");
        jPanel1.add(jp2b, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 350, -1, -1));

        jp3b.setBackground(new java.awt.Color(255, 200, 126));
        buttonGroup5.add(jp3b);
        jp3b.setText("Nelayan");
        jPanel1.add(jp3b, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 350, -1, -1));

        jp4b.setBackground(new java.awt.Color(255, 200, 126));
        buttonGroup5.add(jp4b);
        jp4b.setText("Pensiunan");
        jPanel1.add(jp4b, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 350, -1, -1));

        pd1.setBackground(new java.awt.Color(255, 200, 126));
        buttonGroup6.add(pd1);
        pd1.setText("Dibawah 1,5jt");
        jPanel1.add(pd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 380, -1, -1));

        pd2.setBackground(new java.awt.Color(255, 200, 126));
        buttonGroup6.add(pd2);
        pd2.setText("1,5 - 2,5jt");
        jPanel1.add(pd2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 380, -1, -1));

        pd3.setBackground(new java.awt.Color(255, 200, 126));
        buttonGroup6.add(pd3);
        pd3.setText("2,6 - 3,5jt");
        jPanel1.add(pd3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 380, -1, -1));

        pd4.setBackground(new java.awt.Color(255, 200, 126));
        buttonGroup6.add(pd4);
        pd4.setText("Diatas 3,6jt");
        jPanel1.add(pd4, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 380, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("No. KK");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Nama");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Alamat");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Jenis Kelamin");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Status Pernikahan");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Jumlah Tanggungan");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Usia");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Jenis Pekerjaan");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Pendapatan");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 380, -1, -1));
        jPanel1.add(txtCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 90, -1));

        jToggleButton1.setText("Cari");
        jPanel1.add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 430, -1, -1));

        tblDataWarga.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblDataWarga.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDataWargaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDataWarga);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 460, 890, 120));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String kelamin = null;
        if(jkl.isSelected()){
            kelamin = "Laki-laki";
        }else if(jkp.isSelected()){
            kelamin = "Perempuan";
        }
        
        String statusp = null;
        if(sp1.isSelected()){
            statusp = "Belum Menikah";
        }else if(sp2.isSelected()){
            statusp = "Sudah Menikah";
        }else if(sp3.isSelected()){
            statusp = "Cerai Hidup";
        }else if(sp4.isSelected()){
            statusp = "Cerai Mati";
        }
        
        String jumlaht = null;
        if(jt1.isSelected()){
            jumlaht = "0-1";
        }else if(jt2.isSelected()){
            jumlaht = "2-3";
        }else if(jt3.isSelected()){
            jumlaht = "4-5";
        }else if(jt4.isSelected()){
            jumlaht = "Lebih dari 5";
        }
        
    String usia = null;
        if(us1.isSelected()){
            usia = "Dibawah 31";
        }else if(us2.isSelected()){
            usia = "31-45";
        }else if(us3.isSelected()){
            usia = "46-60";
        }else if(us4.isSelected()){
            usia = "Diatas 60";
        }
        
    String jenisp = null;
        if(jp1a.isSelected()){
            jenisp = "Aparatur/Pejabat Negara";
        }else if(jp1b.isSelected()){
            jenisp = "Wiraswasta";
        }else if(jp2a.isSelected()){
            jenisp = "Tenaga Pengajar";
        }else if(jp2b.isSelected()){
            jenisp = "Tenaga Kesehatan";
        }else if(jp3a.isSelected()){
            jenisp = "Pertanian/Peternakan";
        }else if(jp3b.isSelected()){
            jenisp = "Nelayan";
        }else if(jp4a.isSelected()){
            jenisp = "Belum/Tidak Bekerja";
        }else if(jp4b.isSelected()){
            jenisp = "Pensiunan";
        }
        
        String pendapatan = null;
        if(pd1.isSelected()){
            pendapatan = "Dibawah 1,5jt";
        }else if(pd2.isSelected()){
            pendapatan = "1,5 - 2,5jt";
        }else if(pd3.isSelected()){
            pendapatan = "2,6 - 3,5jt";
        }else if(pd4.isSelected()){
            pendapatan = "Diatas 3,6jt";
        }
        
        String sql ="insert into datawarga values (?,?,?,?,?,?,?,?,?)";
        try{
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1, txtKK.getText());
            stat.setString(2, txtNama.getText());
            stat.setString(3, txtAlamat.getText());
            stat.setString(4, kelamin);
            stat.setString(5, statusp);
            stat.setString(6, jumlaht);
            stat.setString(7, usia);
            stat.setString(8, jenisp);
            stat.setString(9, pendapatan);
            
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "data berhasil disimpan");
            kosong();
            txtKK.requestFocus();
        }
        catch (SQLException e){
            JOptionPane.showMessageDialog(null, "data gagal disimpan"+e);
        }
        datatable();    // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tblDataWargaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDataWargaMouseClicked
    int tabel = tblDataWarga.getSelectedRow();
    txtKK.setText(tblDataWarga.getValueAt(tabel, 0).toString());
    txtNama.setText(tblDataWarga.getValueAt(tabel, 1).toString());
    txtAlamat.setText(tblDataWarga.getValueAt(tabel, 2).toString());
    String a = tblDataWarga.getValueAt(tabel, 3).toString();
    String b = tblDataWarga.getValueAt(tabel, 4).toString();

    if ("Laki-laki".equals(a)){
                jkl.setSelected(true);
            }else {
                jkp.setSelected(true);
            }
    
    if ("Belum Menikah".equals(b)){
                sp1.setSelected(true);
        }else
    if ("Sudah Menikah".equals(b)){
                sp2.setSelected(true);
        }else
    if ("Cerai Hidup".equals(b)){
                sp3.setSelected(true);
        }else{
              sp4.setSelected(true);
              }
    
    // TODO add your handling code here:
    }//GEN-LAST:event_tblDataWargaMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    int ok = JOptionPane.showConfirmDialog(null,"hapus","konfirmasi dialog",JOptionPane.YES_NO_OPTION);
        if (ok==0){
            String sql = "delete from datawarga where nokk ='"+txtKK.getText()+"'";
            try{
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "data berhasil dihapus");
                kosong();
                txtKK.requestFocus();
            }
            catch (SQLException e){
                JOptionPane.showMessageDialog(null, "data gagal dihapus"+e);
        }
       datatable();}    // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    dispose();    // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Datawarga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Datawarga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Datawarga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Datawarga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Datawarga().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JRadioButton jkl;
    private javax.swing.JRadioButton jkp;
    private javax.swing.JRadioButton jp1a;
    private javax.swing.JRadioButton jp1b;
    private javax.swing.JRadioButton jp2a;
    private javax.swing.JRadioButton jp2b;
    private javax.swing.JRadioButton jp3a;
    private javax.swing.JRadioButton jp3b;
    private javax.swing.JRadioButton jp4a;
    private javax.swing.JRadioButton jp4b;
    private javax.swing.JRadioButton jt1;
    private javax.swing.JRadioButton jt2;
    private javax.swing.JRadioButton jt3;
    private javax.swing.JRadioButton jt4;
    private javax.swing.JRadioButton pd1;
    private javax.swing.JRadioButton pd2;
    private javax.swing.JRadioButton pd3;
    private javax.swing.JRadioButton pd4;
    private javax.swing.JRadioButton sp1;
    private javax.swing.JRadioButton sp2;
    private javax.swing.JRadioButton sp3;
    private javax.swing.JRadioButton sp4;
    private javax.swing.JTable tblDataWarga;
    private javax.swing.JTextField txtAlamat;
    private javax.swing.JTextField txtCari;
    private javax.swing.JTextField txtKK;
    private javax.swing.JTextField txtNama;
    private javax.swing.JRadioButton us1;
    private javax.swing.JRadioButton us2;
    private javax.swing.JRadioButton us3;
    private javax.swing.JRadioButton us4;
    // End of variables declaration//GEN-END:variables
}
